### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by nobuyuki83** [poly-bear/pbd2d#3]
When I tried to run the `freebar` program, I got the following error:

I'm using macOS Big Sur version 11.4. 

```bash
Nobuyukis-MacBook-Pro-2:build nobuyuki$ ./Program 
OpenGL Version : 2.1 INTEL-16.4.5
OpenGL Version : 1.20

compile error in vertex shader
ERROR: 0:1: '' :  version '460' is not supported
ERROR: 0:1: '' : syntax error: #version

compile error in fragment shader
ERROR: 0:1: '' :  version '460' is not supported
ERROR: 0:1: '' : syntax error: #version

Segmentation fault: 11
```

**Comment by mmmxyz** [comment]
I add code to specify OpenGL version. please check it works.

**Comment by nobuyuki83** [comment]
Thanks, finally worked! 

![Screen Shot 2021-06-17 at 10 43 25 AM](https://user-images.githubusercontent.com/40525402/122325827-3ce22700-cf66-11eb-9170-7a6820431a68.png)
